<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Quiz extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Quiz $quiz) {
            $quiz->slug = Str::slug($quiz->title);
        });

        self::updating(function (Quiz $quiz) {
            $quiz->slug = Str::slug($quiz->title);
        });
    }

    public function options(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(QuizOption::class, 'quiz_id');
    }
}
